# Generated by Django 5.1.7 on 2025-03-28 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RespireX_User', '0003_apiuser_userprofile_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='apiuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='username',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='account_type',
            field=models.CharField(choices=[('0', 'Free'), ('1', 'Premium'), ('2', 'Enterprise')], default='0', max_length=1),
        ),
    ]
