# Generated by Django 5.1.7 on 2025-03-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RespireX_User', '0005_remove_userprofile_email_remove_userprofile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Prefer to Say')], max_length=1),
        ),
    ]
