# Generated by Django 5.1.7 on 2025-03-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RespireX_User', '0006_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='auth_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
