# Generated by Django 5.1.7 on 2025-03-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RespireX_User', '0007_apiuser_auth_token_apiuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='auth_token',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
