# Generated by Django 5.1.7 on 2025-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RespireX_User', '0008_alter_apiuser_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='history',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
